atom_uid: 01K7CYJ7WZG8ABCCPKQ8TGD5ZG
atom_key: cli/unified-atomic-workflow-tool-agnostic-multi-agent-code-modificat/v1/p04-pr-creation-review-50-atoms/all/310
title: Validate Change Application
role: qa_test_agent
source_doc: ATOMIZED_PROCESSES\Tool-Agnostic Multi-Agent Code Modification Pipeline.md
mode: unspecified
created_at: '2025-10-12T19:32:34.804537+00:00'
