atom_uid: 01K7CZDHF80C6X1VEMXCSCFYXC
atom_key: cli/unified-atomic-workflow-tool-agnostic-multi-agent-code-modificat/v1/p01-unified-planning-analysis-60-atoms/det/086
title: Configure Tool Integrations
role: orchestrator
source_doc: C:\Users\Richard Wilks\CLI_RESTART\tools\atomic-workflow-system\ATOMIZED_PROCESSES\Tool-Agnostic
  Multi-Agent Code Modification Pipeline.md
mode: deterministic
created_at: '2025-10-12T20:51:54.173448+00:00'
