name: Cleanup rollback branches
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Delete rollback branches (gh)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $PSNativeCommandUseErrorActionPreference = $true
          ./scripts/cleanup-rollback-branches.ps1 -UseGh -Repo "$env:GITHUB_REPOSITORY"
